### PR TITLE
feat: global componets for nuxt/ui for `md`

### PR DESCRIPTION
**Pull request by cpreston321**
### 🔗 Linked issue

#49 

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme, or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [X] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Resolves: #49 

This will help us reuse components within nuxt ui that are not global.

### 📝 Checklist

- [X] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by pi0** [comment]
Thanks for PR but is there any specific components missing as global today? Mainly I want to avoid introducing more configuration as much as possible (also consider `.docs` is a nuxt project. One could use `.docs/nuxt.config`.

**Comment by cpreston321** [comment]
@pi0 That is good to know, but since the nuxt/ui is not global we can't use any of the components without exposing them. 

I was trying to use the `UButton` from nuxt/ui that doesn't exist in .md and there is not button component currently. I wanted to keep the theme matching nuxt/ui and pro. Pro only has a handful of other Prose components.

**Comment by cpreston321** [comment]
@pi0 testing the `.docs/nuxt.config` doesn't seem to change or do anything. I tried adding a plugin directory but doesn't do. anything either when testing.

**Comment by pi0** [comment]
I think we might expose `::button` mdc if it is a generic enough component and needed. Extra config in external repos is a no no no!

**Pull request closed without merging**
